
/* autogenerated - do not edit */
#include "jim.h"
#include "jimautoconf.h"

BEGIN_JIM_NAMESPACE

FILE *Jim_AioFilehandle(Jim_Interp *interp, Jim_Obj *command) {
	return NULL;
}

JIM_EXPORT Retval Jim_InitStaticExtensions(Jim_Interp *interp)
{
	return JIM_OK;
}

END_JIM_NAMESPACE
