
/* autogenerated - do not edit */
#include <jim.h>
#include <jimautoconf.h>

BEGIN_JIM_NAMESPACE

JIM_EXPORT Retval Jim_InitStaticExtensions(Jim_InterpPtr interp)

{
    //extern int Jim_posixInit(Jim_InterpPtr );
    //extern int Jim_zlibInit(Jim_InterpPtr );
    //extern int Jim_signalInit(Jim_InterpPtr );
    //extern int Jim_syslogInit(Jim_InterpPtr );

	extern int Jim_stdlibInit(Jim_InterpPtr );
	extern int Jim_aioInit(Jim_InterpPtr );
	extern int Jim_arrayInit(Jim_InterpPtr );
	extern int Jim_clockInit(Jim_InterpPtr );
	extern int Jim_eventloopInit(Jim_InterpPtr );
	//extern int Jim_execInit(Jim_InterpPtr );
	extern int Jim_fileInit(Jim_InterpPtr );
	extern int Jim_historyInit(Jim_InterpPtr );
	extern int Jim_interpInit(Jim_InterpPtr );
	extern int Jim_loadInit(Jim_InterpPtr );
	extern int Jim_namespaceInit(Jim_InterpPtr );
	extern int Jim_nshelperInit(Jim_InterpPtr );
	extern int Jim_ooInit(Jim_InterpPtr );
	extern int Jim_packInit(Jim_InterpPtr );
	extern int Jim_packageInit(Jim_InterpPtr );
	extern int Jim_readdirInit(Jim_InterpPtr );
	extern int Jim_regexpInit(Jim_InterpPtr );
	extern int Jim_tclcompatInit(Jim_InterpPtr );
	extern int Jim_tclprefixInit(Jim_InterpPtr );
	extern int Jim_binaryInit(Jim_InterpPtr );
	extern int Jim_globInit(Jim_InterpPtr );
	extern int Jim_treeInit(Jim_InterpPtr );

    //Jim_signalInit(interp);
    //Jim_syslogInit(interp);
    //Jim_zlibInit(interp);
    //Jim_posixInit(interp);

	Jim_stdlibInit(interp);
	Jim_aioInit(interp);
	Jim_arrayInit(interp);
	Jim_clockInit(interp);
	Jim_eventloopInit(interp);
	//Jim_execInit(interp);
	Jim_fileInit(interp);
	Jim_historyInit(interp);
	Jim_interpInit(interp);
	Jim_loadInit(interp);
	Jim_namespaceInit(interp);
	Jim_nshelperInit(interp);
	Jim_ooInit(interp);
	Jim_packInit(interp);
	Jim_packageInit(interp);
	Jim_readdirInit(interp);
	Jim_regexpInit(interp);
	Jim_tclcompatInit(interp);
	Jim_tclprefixInit(interp);
	Jim_binaryInit(interp);
	Jim_globInit(interp);
	Jim_treeInit(interp);
	return JIM_OK;
}

END_JIM_NAMESPACE
