#pragma once

// Just here to document all the switches you can set.

#define HAVE_LONG_LONG 1
#define HAVE_ARPA_INET_H 1
#define HAVE_CRT_EXTERNS_H 1
#define HAVE_DIRENT_H 1
#define HAVE_DLFCN_H 1
#define HAVE_FCNTL_H 1
#define HAVE_NETDB_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_STDLIB_H 1
#define HAVE_SYSLOG_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_UNISTD_H 1

#define HAVE_BACKTRACE 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_DECL_S_IRWXG 1
#define HAVE_DECL_S_IRWXO 1
#define HAVE_DECL_S_IXUSR 1
#define HAVE_DLOPEN 1
#define HAVE_DLOPEN_COMPAT 1
#define HAVE_DUP 1
#define HAVE_EXECVPE 1
#define HAVE_FCNTL 1
#define HAVE_FORK 1
#define HAVE_FSEEKO 1
#define HAVE_FSYNC 1
#define HAVE_FTELLO 1
#define HAVE_GETADDRINFO 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_GMTIME 1
#define HAVE_INET_NTOP 1
#define HAVE_IOCTL 1
#define HAVE_ISASCII 1
#define HAVE_ISATTY 1
#define HAVE_ISINF 1
#define HAVE_ISNAN 1
#define HAVE_KILL 1
#define HAVE_LFS 1
#define HAVE_LINK 1
#define HAVE_LOCALTIME 1
#define HAVE_LONG_LONG 1
#define HAVE_LSTAT 1
#define HAVE_MKDIR_ONE_ARG 1
#define HAVE_MKSTEMP 1
#define HAVE_OPENDIR 1
#define HAVE_PIPE 1
#define HAVE_PKG_CONFIG 1
#define HAVE_PKG_OPENSSL 1
#define HAVE_PKG_ZLIB 1
#define HAVE_READLINK 1
#define HAVE_REALPATH 1
#define HAVE_REGCOMP 1
#define HAVE_SELECT 1
#define HAVE_SHUTDOWN 1
#define HAVE_SIGACTION 1
#define HAVE_SIN 1
#define HAVE_SLEEP 1
#define HAVE_SOCKET 1
#define HAVE_SOCKETPAIR 1
#define HAVE_STRPTIME 1
#define HAVE_STRPTIME 1
#define HAVE_STRUCT_FLOCK 1
#define HAVE_STRUCT_STAT_ST_MTIM 1
#define HAVE_STRUCT_STAT_ST_MTIMESPEC 1
#define HAVE_STRUCT_SYSINFO_UPTIME 1
#define HAVE_SYMLINK 1
#define HAVE_SYSINFO 1
#define HAVE_SYSLOG 1
#define HAVE_SYSTEM 1
#define HAVE_SYS_SIGLIST 1
#define HAVE_SYS_SIGNAME 1
#define HAVE_TLS_METHOD 1
#define HAVE_UALARM 1
#define HAVE_UMASK 1
#define HAVE_USLEEP 1
#define HAVE_UTIMES 1
#define HAVE_VFORK 1

// mkdir(path) verses mkdir(path,access)
#define HAVE_MKDIR_1ARG 1

#define TCL_LIBRARY "/usr/local/lib/jim"
#define TCL_PLATFORM_OS "linux"
#define TCL_PLATFORM_PATH_SEPARATOR ":"
#define TCL_PLATFORM_PLATFORM "unix"
