#pragma once

//#define PROJ_OS 4
//#define PRJ_OS_64BIT 1
//#define PRJ_OS_LINUX 1
//#define PRJ_COMPILER 2
//#define PRJ_COMPILER_GCC 1
//#define __GNUC__ 9
//#define __linux__ 1

#define HAVE_LONG_LONG 1
#define HAVE_BACKTRACE 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_DIRENT_H 1
#define HAVE_DLOPEN 1
#define HAVE_FCNTL 1
#define HAVE_FORK 1
#define HAVE_FSEEKO 1
#define HAVE_FSYNC 1
#define HAVE_FTELLO 1
#define HAVE_GETEUID 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_IOCTL 1
#define HAVE_ISATTY 1
#define HAVE_KILL 1
#define HAVE_LINK 1
#define HAVE_MKSTEMP 1
#define HAVE_MODE_T_TYPE 1
#define HAVE_OFF_T_TYPE 1
#define HAVE_PID_T_TYPE 1
#define HAVE_READLINK 1
#define HAVE_REALPATH 1
#define HAVE_SHUTDOWN 1
#define HAVE_SLEEP 1
#define HAVE_STRPTIME 1
#define HAVE_STRUCT_TM_TYPE 1
#define HAVE_SYMLINK 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYSLOG_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_UN_H 1
#define HAVE_UALARM 1
#define HAVE_UID_T_TYPE 1
#define HAVE_UMASK 1
#define HAVE_UNISTD_H 1
#define HAVE_USECONDS_T_TYPE 1
#define HAVE_USLEEP 1
#define HAVE_UTIMES 1
#define HAVE_VFORK 1
#define HAVE_STRUCT_SYSINFO_UPTIME 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_NETDB_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_SYS_SYSINFO_H 1
#define HAVE_WAITPID 1

#define TCL_LIBRARY "/usr/local/lib/jim"
#define TCL_PLATFORM_OS "linux"
#define TCL_PLATFORM_PATH_SEPARATOR ":"
#define TCL_PLATFORM_PLATFORM "unix"
